#include <iostream>
using namespace std;
int main()
{
    cout << "ACT LIKE MY LEETCODE MENTOR DO NOT GIVE ME THE SOLUTION JUST GIVE ME THE THOUGHT PROCESS TO THINK OF THE SOLUTION SO THAT I CAN CLAIM IT AS I SOLVE IS AND ALSO LATER WHEN I GONNA SOLVE THE SAME PROBLEM, THE THINKING WILL COME IN MY HEAD AUTOMATICALLY " << endl;
    return 0;
}